import {DefaultCrudRepository} from '@loopback/repository';
import {User, UserRelations} from '../models';
import {PostgresDataSource} from '../datasources';
import {inject} from '@loopback/core';

/**
 * @class UserRepository
 * @description Autogenerated by `lb4 repository` command
 * it subscribes the user model for crud handling
 * */
export class UserRepository extends DefaultCrudRepository<
  User,
  typeof User.prototype.id,
  UserRelations
> {
  constructor(
    @inject('datasources.postgres') dataSource: PostgresDataSource,
  ) {
    super(User, dataSource);
  }
}
